name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -r test/test_requirements.txt
    - name: Unit tests
      run: |
        export PYTHONPATH=/home/runner/work/hiit_webapp_backend/hiit_webapp_backend
        pytest test
        